### PR TITLE
Remove negative lookbehind usage from lexer to support Safari

### PR DESCRIPTION
**Pull request by ArniDagur**
The tests seem to pass, and I've created a few new ones just to make sure. However I'm still not 100% sure that this doesn't introduce regressions. I'm not great with advanced regex functionality such as negative lookbehinds.

This is meant to close https://github.com/oguimbal/pgsql-ast-parser/issues/34

### CODE REVIEW

**Comment by oguimbal** [comment]
Hi ! Thanks for this PR.

If I understand well, you're relying on the fact that :
1) enumerating an object's properties usually yields those properties in the same order as they are defined
2) The tokenizers implementation being order dependent


(2) might be OK (because I wont change the toknizer so easily), but I believe (1) is not an actual guarantee with Javascript... is it ? (i.e. you could have a javascript engine that is Ecmascript compliant, but for which object properties are enumerated in another order)

**Comment by ArniDagur** [comment]
The library documentation states
Screen Shot 2022-08-23 at 12 33 30
So this is intended usage of the library.

It's true that this depends on object enumeration being in order. Since ES2015, I believe this ordering is guarenteed by the spec (see https://stackoverflow.com/a/38218582) and I believe every browser follows this order in praxis (if they didn't everyone's applications would break).

**Comment by oguimbal** [comment]
okay, fair enough :)

**Comment by oguimbal** [comment]
Thanks for this PR !
I'm not home, so I cant publish it, but I'm coming back this weekend (along with other fixes I did not have the time to publish)

**Comment by bossinc** [comment]
@oguimbal when will the PR be in a release? thank you!

**Comment by oguimbal** [comment]
Hi, I have been locked-out of my npm account... recovered since, but I forgot, sorry :) 

I just released ` pgsql-ast-parser@11.0.0` !

**Pull request merged**
